<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\Directory.Build.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>PlugHub.Wpf</AssemblyName>
    <RootNamespace>PlugHub.Wpf</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PlugHub.Contracts\PlugHub.Contracts.csproj" />
    <ProjectReference Include="..\PlugHub.Framework\PlugHub.Framework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\LOGO.png" LogicalName="PlugHub.Wpf.Resources.LOGO.png" />
    <EmbeddedResource Include="Resources\SETTINGS.png" LogicalName="PlugHub.Wpf.Resources.SETTINGS.png" />
  </ItemGroup>
</Project>
