<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\Directory.Build.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>PlugHub.Uninstaller</AssemblyName>
    <RootNamespace>PlugHub.Uninstaller</RootNamespace>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
