<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\Directory.Build.props" />

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>PlugHub.Updater</AssemblyName>
    <RootNamespace>PlugHub.Updater</RootNamespace>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>
</Project>
