<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\Directory.Build.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>PlugHub.Manager</AssemblyName>
    <RootNamespace>PlugHub.Manager</RootNamespace>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PlugHub.Contracts\PlugHub.Contracts.csproj" />
    <ProjectReference Include="..\PlugHub.Framework\PlugHub.Framework.csproj" />
    <ProjectReference Include="..\PlugHub.Wpf\PlugHub.Wpf.csproj" />
  </ItemGroup>
</Project>
